### ISSUE TITLE
Error loading shared library libpython2.7.so.1.0: Permission denied (needed by /usr/bin/python)

### ISSUE THREAD

**Issue by cloneMe** [linuxserver/docker-htpcmanager#8]
Hello,

I have cloned your project because I would like to add a parameter WEB_DIR (http://htpc.io/installation.html) 
I haven't modified your project and I have an error :/
To launch it, I'm using the following docker-compse:
```
version: '2'
services:

 htpcmanager:
#    image: linuxserver/htpcmanager
    build: ../docker-htpcmanager
    container_name: tool_HTPCManager
    restart: always
    environment:
      - TZ=Europe/Paris
      - WEB_DIR="/htpc"
      - PUID=1001
      - PGID=1001
```

Please find docker logs:
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-install: executing... 
Cloning into '/app/htpcmanager'...
[cont-init.d] 30-install: exited 0.
[cont-init.d] done.
[services.d] starting services
Zero database found, adding available interfaces...
[services.d] done.
Error loading shared library libpython2.7.so.1.0: Permission denied (needed by /usr/bin/python)
Error relocating /usr/bin/python: Py_Main: symbol not found

OS: CentOS 
To note: using image: linuxserver/htpcmanager, it works.

Thanks for the help
